language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"

# command to install dependencies
install: "pip install -r requirements/development.txt"

# command to run tests
script:
    - coverage run -m nose
    - flake8

# coverage!
after_success:
    coveralls

deploy:
  provider: heroku
  api_key:
    secure: C5MxDoGaz+//EWWsbKLUp0jHSAj96e8lQ4x1r6brDmDrOnxZm/8cX0twLEOLem4WG7cId29o7ZIFO7lmaWo1RMNyShvbzesTChlUJHCP5ZhoGQJPxmVjJzhyNYfrNXzF0vd2iTZw9k6PbPBKpGHnhWSfWbdyqzeIAvmSPAJmLSM=
  app: underquotedbot
  on:
    repo: jessamynsmith/underquotedbot
